{
  "guiPortIfTNum": "8",
  "guiPortIfT": [
    {
      "gid": 1001,
      "port": 1,
      "name": "GE1",
      "type": 1,
      "address": "1.2.3.4",
      "netmask": "255.255.255.0",
      "dhcpPool": "GE1_DHCP_POOL",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:b34f:1e85::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1002,
      "port": 2,
      "name": "GE2",
      "type": 0,
      "address": "1.2.3.5",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:b3aa:1e20::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1003,
      "port": 3,
      "name": "GE3",
      "type": 0,
      "address": "1.2.3.6",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:be3f:1a8d::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1004,
      "port": 4,
      "name": "GE4",
      "type": 0,
      "address": "1.2.3.10",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fde3:b56f:1125::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1005,
      "port": 5,
      "name": "GE5",
      "type": 0,
      "address": "1.2.5.4",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:b324:1e21::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1006,
      "port": 6,
      "name": "GE6",
      "type": 0,
      "address": "1.6.3.4",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:b34a:3483::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1007,
      "port": 7,
      "name": "GE7",
      "type": 0,
      "address": "7.2.3.4",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:b3af:1e23::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    },
    {
      "gid": 1008,
      "port": 8,
      "name": "GE8",
      "type": 0,
      "address": "1.8.3.4",
      "netmask": "255.255.255.0",
      "dhcpPool": "",
      "speed": 1000,
      "duplex": 0,
      "flowControl": 0,
      "mtuMode": 0,
      "mtuValue": 1500,
      "linkStatus": 1,
      "zoneId": 9990,
      "ipv6Address":"fd7a:5553:1eaa::1",
      "ipv6PrefixLength":64,
      "cgiAction": 0
    }
  ],
  "guiIpAliasTNum": 8,
  "guiIpAliasT": [
    {
      "ipAliasCnt": 2,
      "address": "9.9.9.9;8.8.8.8",
      "netmask": "255.255.255.0;255.0.0.0"
    },
    {
      "ipAliasCnt": 1,
      "address": "4.4.4.4",
      "netmask": "255.255.0.0"
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    },
    {
      "ipAliasCnt": 0,
      "address": "",
      "netmask": ""
    }
  ],
  "guiDhcpsTNum": 8,
  "guiDhcpsT": [
    {
      "gid": 2000,
      "type": 1,
      "startIp": "1.2.3.100",
      "endIp": "1.2.3.200",
      "relayIp": "",
      "leaseTime": "1440",
      "gateway": "1.2.3.4",
      "dns1": "8.8.8.8",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": "myDomain"
    },
    {
      "gid": 2001,
      "type": 2,
      "startIp": "",
      "endIp": "",
      "relayIp": "1.2.3.4",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2002,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2003,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2004,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2005,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2006,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    },
    {
      "gid": 2007,
      "type": 0,
      "startIp": "",
      "endIp": "",
      "relayIp": "",
      "leaseTime": "",
      "gateway": "",
      "dns1": "",
      "dns2": "",
      "wins1": "",
      "wins2": "",
      "domainName": ""
    }
  ]
} 

