{
    "guiRulesTNum": "6",
    "guiRulesT": [
        {
            "gid": "999000",
            "enabled": "1",
            "fromZone": "9990",
            "toZone": "9999",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "70",
            "hitCount": "199",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        },
        {
            "gid": "999009",
            "enabled": "0",
            "fromZone": "9997",
            "toZone": "9990",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "90",
            "hitCount": "299",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        },
        {
            "gid": "999008",
            "enabled": "1",
            "fromZone": "9998",
            "toZone": "9990",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "90",
            "hitCount": "299",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        },
        {
            "gid": "999007",
            "enabled": "0",
            "fromZone": "9990",
            "toZone": "9997",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "90",
            "hitCount": "299",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        },
        {
            "gid": "999001",
            "enabled": "0",
            "fromZone": "9998",
            "toZone": "9997",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "90",
            "hitCount": "299",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        },
        {
            "gid": "999002",
            "enabled": "1",
            "fromZone": "1048577",
            "toZone": "1048578",
            "service": "4710",
            "application": "",
            "url": "",
            "sourceAddress": "10",
            "sourceUser": "",
            "destinationAddress": "0",
            "destinationUser": "",
            "schedule": "110",
            "hitCount": "399",
            "log": "1",
            "matchAction": "0",
            "cgiAction": "0"
        }
    ]
}
